name: Compile
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Run build.
              run: make -B && ./paleta < palettes/base16-default-dark
